engines:
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  fixme:
    enabled: true
ratings:
  paths:
  - client/**
  - server/**
exclude_paths:
    - "node_modules/**/*"
    - "img/**/*"
    - "**/vendor/**/*"
    - "**/config/**/*"
    - "**/test/**/*"
    - "server/*.js"
    - "client/*.js"
    - "./*.js"
    - "server/src/main/middleware/bootstrapMiddleware.js"
    - "server/src/main/middleware/routesMiddleware.js"
    - "**/resources/**/*"
    - "**/coverage/**/*"
    - "**/mock/**/*"
    - "**/lib/**/*"
