engines:
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
exclude_paths:
    - "**/node_modules/"
    - "**/img/"
    - "**/vendor/*"
